name: Github CI

on: workflow_dispatch

jobs:
  regenerate-formula:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: |
        ./scripts/regenerate-advent-of-code.py > Formula/advent-of-code.rb
        git config --global user.email "ci@example.com"
        git config --global user.name "CI Bot"
        git add Formula/advent-of-code.rb
        git commit -m 'Bump advent-of-code formula'
        git push
