name: Github CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        type: string

jobs:
  regenerate-formula:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: |
        ./scripts/regenerate-advent-of-code.py > Formula/advent-of-code.rb
        git config --global user.email "ci@example.com"
        git config --global user.name "CI Bot"
        git add Formula/advent-of-code.rb
        git commit -m 'Bump advent-of-code formula'
        git push
      env:
        ADVENT_OF_CODE_VERSION: ${{ inputs.version }}

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }}
