name: Scheduled

on:
  schedule:
  - cron: '0 23 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: scripts/check-update.py
    - run: |
        git config --global user.email "ci@example.com"
        git config --global user.name "CI Bot"
        git add .
        if git commit -m 'Update formulas from scheduled job'; then git push; fi
